on: [push,pull_request]

name: Deploy Site
jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build, Check, Deploy'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build and Deploy Nikola
      uses: WWU-AMM/nikola-action@v4.1.1
      with:
        dry_run: ${{ github.ref_name != 'main' }}
